apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 10%
  selector:
    matchLabels:
      app: webserver
      tier: frontend
  template:
    metadata:
      labels:
        app: webserver
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.10.0
          resources:
            limits:
              cpu: 10m
              memory: 64Mi
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
